### PR TITLE
Flappybird practice problem

### PR DESCRIPTION
**Pull request by chrehall68**
Add a few instructions and a few descriptions so that students can create the intended flappy bird game (building off of the given code)

This pr is to solve issue #153

### CODE REVIEW

**Review by BenVN123 — APPROVED** [review]

**Comment by chrehall68** [comment]
@alyona-vishnoi can you take a look at the pr? Do you think enough instructions are provided?

**Comment by alyona-vishnoi** [comment]
> @alyona-vishnoi can you take a look at the pr? Do you think enough instructions are provided?

yup, looks good!

**Review by alyona-vishnoi — APPROVED** [review]

**Review by PavithraY22 — APPROVED** [review]
Yep looks good. Just a suggestion maybe we can add what concepts or tools the person needs to complete the game so they know what to focus on.

**Comment by chrehall68** [comment]
> Yep looks good. Just a suggestion maybe we can add what concepts or tools the person needs to complete the game so they know what to focus on.

Ok then @PavithraY22 , could you add that then?

**Comment by chrehall68** [comment]
@PavithraY22  - merging this pr, but you can make another pr that adds what concepts or tools the person needs to complete the game.

**Pull request merged**
