### PR TITLE
reset-position

### PR DESCRIPTION
**Pull request by shiventi**
## Location

Specify chapters and sections here.

- Chapter(s): #
- Section(s): #.#

## Changes

- List any changes here and explanations for why they're needed (if it's not obvious)

## Notes

- Add any notes here for the Curriculum Development team

**Add all relevant labels to this PR (e.g. if it's about a practice problem, add the practice problem label)**

### CODE REVIEW

**Review by hpanchal092 — CHANGES_REQUESTED** [review]
code itself looks good, we should add the problem specifications as comments to the top of the files, these are the same specifications we'll put on notion.

**Comment by chrehall68** [comment]
I think that we should try to enforce the pygame.Rect standard since we use that more in later examples (ie use pygame.Rect class instead of just the x,y,width,height tuple)

**Review by chrehall68 — APPROVED** [review]
LGTM now. I think the instructions are clear and match the problem that was solved with the original

**Review by hpanchal092 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
