### PR TITLE
Games ch3

### PR DESCRIPTION
**Pull request by TomM-and-jerry**
## Location

Specify chapters and sections here.

- Chapter(s): GUI Chapter 3
- Section(s): Practice problems

## Changes
Added solution files to practice problems
Problem 1: Quit Pygame
Problem 2: Move Rectangle

- List any changes here and explanations for why they're needed (if it's not obvious)

## Notes

- Add any notes here for the Curriculum Development team

**Add all relevant labels to this PR (e.g. if it's about a practice problem, add the practice problem label)**

### CODE REVIEW

**Review by chrehall68 — CHANGES_REQUESTED** [review]
Currently, these are solutions. That's good that you have solutions, but please: 
move them to a solutions folder under chapter3 
add instructions as either comments or a docstring to the top of each file
under the 'practice' folder, put instructions and any starting code. (similar to how it is done in the regular course)

**Review by chrehall68 — COMMENTED** [review]
Looks mostly good now. However, I think there may be a bug in the MoveRectProblem.py since when I hold down the arrow keys, they don't keep moving the rectangle (but when I hold down w, a, s, or d, they continue to move the rectangle). Does this happen to anyone else?

**Review by chrehall68 — CHANGES_REQUESTED** [review]
If the movement bug is actually a bug, we should fix that. Then, we can merge this pr.

**Comment by alyona-vishnoi** [comment]
> Looks mostly good now. However, I think there may be a bug in the MoveRectProblem.py since when I hold down the arrow keys, they don't keep moving the rectangle (but when I hold down w, a, s, or d, they continue to move the rectangle). Does this happen to anyone else?

We may need to add key up events as well as booleans to be able to move the rectangle. If we don't want a, w, d,s to keep moving the rectangle- we just have to change the indentation of the keyPressed events.

**Comment by BenVN123** [comment]
> If the movement bug is actually a bug, we should fix that. Then, we can merge this pr.

Fixed it.

**Review by chrehall68 — APPROVED** [review]
Movement works. LGTM now.

**Review by alyona-vishnoi — APPROVED** [review]

**Pull request merged**
