### PR TITLE
Clarify instructions for Ch. 5 exercises

### PR DESCRIPTION
**Pull request by phrdang**
Updated instructions for Add All the Way and Up 2 Fifty

### CODE REVIEW

**Comment by abhatia1205** [comment]
Fix watever the linting error is @phrdang

**Comment by phrdang** [comment]
> Fix watever the linting error is @phrdang

Yeah I fixed the workflow so Lintly works properly. As for the flake8 lint, when the last PR went in, it caught these errors:
Screen Shot 2020-07-14 at 10 05 07 AM
So I split the long lines into mutliple lines, but then the Black formatter put them back in one line so I was just like eh whatever.
So now the flake8 workflow will only fail on new errors, which is why all the checks should now pass. Not sure if it automatically can un-request changes...

**Comment by phrdang** [comment]
Okay @abhatia1205 on second thought I can make it so that Black does max line length of 79 like what flake8 is doing. Hold on a sec...

**Comment by phrdang** [comment]
Alright @abhatia1205 @Patel-Dev should be good now for the Python checks

**Review by Patel-Dev — APPROVED** [review]
Looks good to me.

**Pull request merged**
